### ISSUE TITLE
8MB flash variant

### ISSUE THREAD

**Issue by davefes** [nspsck/STM32F411CEU6_BlackPill_Micropython#12]
In preparation for the arrival of some 8MB boards I would like to know if the flash chip on my previous version should build.

`winbond 25Q64JVSIQ`

I seem to have problems with `rshell` talking to these boards.

Thank you.

**Comment by nspsck** [comment]
Hi, 

I am not the developer of rshell, hence I have very little idea about its behavior. The firmware should work just fine with mpremote and thonny. And these are where my focus lies. Since I have very little time due to work/life situation, I can't afford to maintain someone else's project, aka `rshell`. I hope you can understand.

And for the new boards you are receiving: they should work with 8MB versions of firmwares. Both 8MHz crystal one or 25MHz crystal one have their firmware provided. By "work" I meant on mpremote and thonny.

Best regards

**Comment by davefes** [comment]
Could you tell me the part number of the flash on your 8MB boards?

**Comment by nspsck** [comment]
It's something similar, if not then exactly the same thing. I have also ordered some w25q64jvssiq to solder on these 8MHz boards and these works too.

**Comment by davefes** [comment]
`w25q64jvssiq` seem to be similar to `w25q64jvsiq`, well at least from my reading.

Thank you.
